'use client';
import {useEffect,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { Menu, ShoppingBag, X, ArrowUpRight, ArrowRight, Plus, Minus, Check, Search, FlaskConical, ArrowDown, Trash2 } from 'lucide-react';
import {products,families,money, type Product,type Family} from '@/lib/products';
import ProductArt from './product-art';
import Motion from './motion';
type CartLine={id:string;size:30|50|100;quantity:number};
const priceFor=(p:Product,size:number)=>Math.round(p.price*(size===30?.65:size===100?1.55:1));
function Modal({open,onOpenChange,title,children,kind='modal'}:{open:boolean;onOpenChange:(v:boolean)=>void;title:string;children:React.ReactNode;kind?:string}) {return <Dialog.Root open={open} onOpenChange={onOpenChange}><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className={kind} data-lenis-prevent aria-describedby={undefined}><Dialog.Title className="sr-only">{title}</Dialog.Title><Dialog.Close className="icon-button close" aria-label="Close"><X size={21}/></Dialog.Close>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>}
export default function Storefront(){
const [menu,setMenu]=useState(false),[bag,setBag]=useState(false),[selected,setSelected]=useState<Product|null>(null),[size,setSize]=useState<30|50|100>(50),[family,setFamily]=useState<Family>('All scents'),[search,setSearch]=useState(''),[expanded,setExpanded]=useState(false),[cart,setCart]=useState<CartLine[]>([]),[loaded,setLoaded]=useState(false),[toast,setToast]=useState(''),[info,setInfo]=useState<string|null>(null),[review,setReview]=useState(false);
useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('mooko-bag')||'[]');if(Array.isArray(saved))setCart(saved.filter((l:CartLine)=>products.some(p=>p.id===l.id)&&[30,50,100].includes(l.size)&&Number.isInteger(l.quantity)&&l.quantity>0).map((l:CartLine)=>({...l,quantity:Math.min(l.quantity,20)})));}catch{}setLoaded(true);},[]);
useEffect(()=>{if(loaded)localStorage.setItem('mooko-bag',JSON.stringify(cart));},[cart,loaded]);
useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(t);},[toast]);
const count=cart.reduce((s,l)=>s+l.quantity,0),total=cart.reduce((s,l)=>s+priceFor(products.find(p=>p.id===l.id)!,l.size)*l.quantity,0);
const openProduct=(p:Product)=>{setSelected(p);setSize(50);};
const add=(p:Product)=>{setCart(c=>{const existing=c.find(l=>l.id===p.id&&l.size===size);return existing?c.map(l=>l===existing?{...l,quantity:Math.min(20,l.quantity+1)}:l):[...c,{id:p.id,size,quantity:1}];});setSelected(null);setToast(`${p.name} added to your bag`);};
const changeQty=(i:number,d:number)=>setCart(c=>c.map((l,j)=>j===i?{...l,quantity:Math.min(20,l.quantity+d)}:l).filter(l=>l.quantity>0));
const chooseFamily=(f:Family)=>{setFamily(f);setExpanded(true);document.getElementById('shop')?.scrollIntoView({behavior:'smooth'});};
const filtered=products.filter(p=>(family==='All scents'||p.family===family)&&`${p.name} ${p.notes.join(' ')}`.toLowerCase().includes(search.toLowerCase()));
const visible=(expanded||search||family!=='All scents')?filtered:filtered.slice(0,6);
return <><Motion/><a className="skip-link" href="#shop">Skip to products</a>
<div className="announcement"><FlaskConical size={12}/><span>A little luxury. A lasting impression.</span><button onClick={()=>setInfo('Our philosophy')}>Discover MOOKO <ArrowUpRight size={12}/></button></div>
<main>
<section className="hero" id="home"><img className="hero-photo" src="/images/hero.png" alt="MOOKO Velour Dark Gold perfume with amber silk and a golden cap" fetchPriority="high"/>
<header className="header"><button className="icon-button" aria-label="Open navigation" onClick={()=>setMenu(true)}><Menu size={19}/></button><a className="wordmark" href="#home" aria-label="MOOKO home">MOOKO</a><button className="icon-button bag-button" aria-label={`Open shopping bag, ${count} items`} onClick={()=>{setBag(true);setReview(false);}}><ShoppingBag size={18}/>{count>0&&<span className="bag-count">{count}</span>}</button></header>
<div className="hero-copy"><h1>Amazing scent that<br/>reflects <span>character</span></h1><p>Mooko delivers distinctive fragrances with an elegant,<br className="desktop-br"/> modern touch — made for those who stand out.</p><div className="actions"><a className="button black" href="#collections">Discover collection <ArrowUpRight size={15}/></a><button className="button white" onClick={()=>setInfo('Contact us')}>Contact us</button></div></div>
<button className="hero-product" onClick={()=>openProduct(products[6])}><span className="pill">• New</span><strong>Velour Dark Gold</strong><span>Luxury, richness, warmth</span><b>{money(120)}</b><ArrowUpRight className="product-arrow" size={18}/></button><a className="hero-scroll" href="#collections" aria-label="Explore collections"><ArrowDown size={18}/></a>
</section>
<section className="collections section" id="collections"><div className="section-heading" data-reveal><span className="eyebrow">Our collections</span><h2>Discover the fragrance with<br/>an unlimited collection</h2></div><div className="collection-grid">{(['Warm & woody','Fresh & citrus','Soft & floral'] as Family[]).map((f,i)=><button className="collection-card" key={f} data-reveal onClick={()=>chooseFamily(f)}><ProductArt cell={i} name={`${f} fragrance collection`}/><span className="collection-tag">{['Rich & sensual','Bright & effortless','Soft & expressive'][i]}</span><div className="collection-caption"><div><span>THE COLLECTION</span><h3>{f}</h3></div><span className="round-arrow"><ArrowUpRight size={22}/></span></div></button>)}</div></section>
<section className="ingredients" id="story"><div className="botanicals" aria-hidden="true">{['Neroli','Lemon','Star anise','Rose','Lavender','Jasmine'].map((n,i)=><div key={n} className={`botanical botanical-${i}`} style={{backgroundPosition:`${(i%3)*50}% ${Math.floor(i/3)*100}%`}}/>)}</div><div className="ingredients-copy" data-reveal><span className="outline-pill">Soulful creations. Beautiful ingredients.</span><h2>Only high-quality<br/>parfume ingredients</h2><p>We create perfumes that can be enjoyed to the fullest,<br className="desktop-br"/> using ingredients whose quality is beyond doubt.</p><button className="button white" onClick={()=>setInfo('Our story')}>View our story <ArrowUpRight size={14}/></button></div></section>
<section className="products section" id="shop"><div className="section-heading" data-reveal><span className="eyebrow">Our products</span><h2>We know you love lots of<br/>scents, discover them now</h2></div><div className="shop-tools"><div className="filters" aria-label="Filter by scent family">{families.map(f=><button key={f} aria-pressed={family===f} onClick={()=>setFamily(f)} className={family===f?'active':''}>{f}</button>)}</div><label className="search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find your scent" aria-label="Search fragrances"/></label></div><div className="product-grid">{visible.map(p=><article className="product-card" key={p.id}><button className="product-image-button" onClick={()=>openProduct(p)} aria-label={`View ${p.name}`}><ProductArt cell={p.cell} name={`${p.name} eau de parfum`}/>{p.isNew&&<span className="pill product-badge">• New</span>}{p.previous&&<span className="discount">15% OFF</span>}<span className="quick-view">Discover scent <Plus size={18}/></span></button><div className="product-details"><button onClick={()=>openProduct(p)}><h3>{p.name}</h3></button><p>{p.mood}</p><div className="price">{money(p.price)} {p.previous&&<del>{money(p.previous)}</del>}</div><button className="quick-add icon-button" aria-label={`Choose size for ${p.name}`} onClick={()=>openProduct(p)}><Plus size={18}/></button></div></article>)}</div>{visible.length===0&&<div className="empty-state"><h3>No scents found.</h3><p>Try a different name or explore all our fragrances.</p><button className="button black" onClick={()=>{setSearch('');setFamily('All scents');}}>View all scents</button></div>}{!expanded&&!search&&family==='All scents'&&<button className="button black more" onClick={()=>setExpanded(true)}>Find more perfume <ArrowRight size={15}/></button>}</section>
<section className="closing" data-reveal><div><span className="eyebrow">A SCENT OF YOUR OWN</span><h2>Leave a little<br/>of <span>yourself</span> everywhere.</h2></div><a className="button black" href="#shop">Find your signature <ArrowUpRight size={16}/></a></section>
</main><footer><div className="footer-main"><a className="footer-logo" href="#home">MOOKO</a><p>Fragrance that feels like you.<br/>Memories that stay.</p><div><a href="#collections">Collections</a><a href="#shop">All fragrances</a><button onClick={()=>setInfo('Our story')}>Our story</button></div><div><button onClick={()=>setInfo('Fragrance care')}>Fragrance care</button><button onClick={()=>setInfo('Shipping & returns')}>Shipping & returns</button><button onClick={()=>setInfo('Contact us')}>Contact us</button></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} MOOKO. All rights reserved.</span><span>Thoughtfully composed. Personally worn.</span><button onClick={()=>setInfo('Privacy')}>Privacy</button></div></footer>
<Modal open={menu} onOpenChange={setMenu} title="Navigation" kind="drawer menu-drawer"><a className="wordmark" href="#home" onClick={()=>setMenu(false)}>MOOKO</a><nav>{[['The collection','#collections'],['Shop fragrances','#shop'],['Our ingredients','#story']].map(([label,url],i)=><a href={url} onClick={()=>setMenu(false)} key={url}><small>0{i+1}</small>{label}<ArrowUpRight/></a>)}</nav><p>A scent of your own.</p></Modal>
<Modal open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}} title={selected?.name||'Product details'} kind="modal product-modal">{selected&&<><ProductArt cell={selected.cell} name={selected.name}/><div className="product-modal-copy"><span className="eyebrow">EAU DE PARFUM · {selected.family}</span><h2>{selected.name}</h2><p className="modal-price">{money(priceFor(selected,size))}</p><p>{selected.description}</p><div className="notes">{selected.notes.map(n=><span key={n}>{n}</span>)}</div><fieldset><legend>Select size</legend><div className="sizes">{([30,50,100] as const).map(s=><button key={s} aria-pressed={size===s} className={size===s?'chosen':''} onClick={()=>setSize(s)}>{s} ml</button>)}</div></fieldset><button className="button black add-to-bag" onClick={()=>add(selected)}>Add to bag — {money(priceFor(selected,size))}<Plus size={18}/></button><p className="fine-print">Eau de parfum · Select your preferred size</p></div></>}</Modal>
<Modal open={bag} onOpenChange={setBag} title="Your shopping bag" kind="drawer bag-drawer"><h2>{review?'Order summary':'Your shopping bag'} <span>({count})</span></h2>{cart.length?<><div className="bag-lines">{cart.map((l,i)=>{const p=products.find(p=>p.id===l.id)!;return <div className="bag-line" key={`${l.id}-${l.size}`}><ProductArt cell={p.cell} name={p.name}/><div><h3>{p.name}</h3><p>Eau de parfum · {l.size} ml</p><strong>{money(priceFor(p,l.size))}</strong><div className="quantity"><button aria-label={`Decrease ${p.name} quantity`} onClick={()=>changeQty(i,-1)}><Minus size={13}/></button><span>{l.quantity}</span><button disabled={l.quantity>=20} aria-label={`Increase ${p.name} quantity`} onClick={()=>changeQty(i,1)}><Plus size={13}/></button></div></div><button className="remove" aria-label={`Remove ${p.name}`} onClick={()=>setCart(c=>c.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div>;})}</div><div className="bag-summary"><div><span>Subtotal</span><strong>{money(total)}</strong></div><p>Shipping and taxes calculated at checkout.</p>{review?<div className="checkout-notice"><strong>This storefront is a preview.</strong><p>Payments and order fulfillment are not connected. No order has been placed and no payment is collected.</p><button className="button black" onClick={()=>setReview(false)}>Back to bag</button></div>:<button className="button black" onClick={()=>setReview(true)}>Review order <ArrowRight size={17}/></button>}</div></>:<div className="empty-bag"><ShoppingBag size={40} strokeWidth={1}/><h3>Your next signature awaits.</h3><p>Discover a fragrance that feels like you.</p><button className="button black" onClick={()=>{setBag(false);document.getElementById('shop')?.scrollIntoView({behavior:'smooth'});}}>Explore fragrances</button></div>}</Modal>
<Modal open={!!info} onOpenChange={v=>{if(!v)setInfo(null);}} title={info||'About MOOKO'}><div className="info-copy"><span className="eyebrow">MOOKO</span><h2>{info}</h2>{info==='Contact us'?<><p>We would love to help you find your signature scent.</p><p>This is a demonstration storefront. Store contact details will be added by the merchant before launch.</p><button className="button black" onClick={()=>{setInfo(null);document.getElementById('shop')?.scrollIntoView({behavior:'smooth'});}}>Explore the collection</button></>:info==='Shipping & returns'?<><p>Shipping destinations, delivery times and return eligibility will be confirmed by the merchant before the store opens.</p><p>This preview does not accept payments or place orders.</p></>:info==='Privacy'?<><p>Your shopping bag is saved only in this browser so it is here when you return. This preview does not collect account or payment information and does not use analytics cookies.</p><button className="button black" onClick={()=>{setCart([]);localStorage.removeItem('mooko-bag');setToast('Your saved shopping bag has been cleared');}}>Clear saved bag</button></>:info==='Fragrance care'?<><p>Keep your fragrance away from direct sunlight, heat and humidity. Store it upright, with its cap securely closed.</p><p>Apply lightly to pulse points and allow it to settle without rubbing. Avoid contact with eyes or irritated skin.</p></>:<><p>A fragrance is more than what you wear. It is a feeling, a memory, a little piece of who you are.</p><p>MOOKO explores the space between familiar and unexpected — luminous citrus, delicate florals and the quiet warmth of woods. Discover a composition that feels entirely your own.</p><div className="story-notes"><span>01 · Thoughtful compositions</span><span>02 · Distinctive character</span><span>03 · Everyday moments</span></div></>}</div></Modal>
<div className={`toast ${toast?'show':''}`} role="status" aria-live="polite">{toast&&<><Check size={17}/>{toast}<button onClick={()=>{setBag(true);setReview(false);setToast('');}}>View bag</button></>}</div>
</>;
}
